GET http://localhost:3000/products

###

GET http://localhost:3000/products/633bf04bd17b8091d5fe6d52


###

POST http://localhost:3000/products
Content-Type: application/json

{
    "brand": "Coop",
    "typeOfProduct": "cleaner"
}


###

DELETE http://localhost:3000/products/633bf04bd17b8091d5fe6d52

###

PATCH http://localhost:3000/products/633bf023d17b8091d5fe6d50
Content-Type: application/json

{
    "brand": "New Brand"
}



